// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fnrun.proto

package protobufs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnvironmentVariable struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvironmentVariable) Reset()         { *m = EnvironmentVariable{} }
func (m *EnvironmentVariable) String() string { return proto.CompactTextString(m) }
func (*EnvironmentVariable) ProtoMessage()    {}
func (*EnvironmentVariable) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5c3996a00beb420, []int{0}
}

func (m *EnvironmentVariable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentVariable.Unmarshal(m, b)
}
func (m *EnvironmentVariable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentVariable.Marshal(b, m, deterministic)
}
func (m *EnvironmentVariable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentVariable.Merge(m, src)
}
func (m *EnvironmentVariable) XXX_Size() int {
	return xxx_messageInfo_EnvironmentVariable.Size(m)
}
func (m *EnvironmentVariable) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentVariable.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentVariable proto.InternalMessageInfo

func (m *EnvironmentVariable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnvironmentVariable) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Event struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5c3996a00beb420, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExecutionContext struct {
	StopTime             *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=stopTime,proto3" json:"stopTime,omitempty"`
	EnvVars              []*EnvironmentVariable `protobuf:"bytes,2,rep,name=envVars,proto3" json:"envVars,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ExecutionContext) Reset()         { *m = ExecutionContext{} }
func (m *ExecutionContext) String() string { return proto.CompactTextString(m) }
func (*ExecutionContext) ProtoMessage()    {}
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5c3996a00beb420, []int{2}
}

func (m *ExecutionContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionContext.Unmarshal(m, b)
}
func (m *ExecutionContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionContext.Marshal(b, m, deterministic)
}
func (m *ExecutionContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionContext.Merge(m, src)
}
func (m *ExecutionContext) XXX_Size() int {
	return xxx_messageInfo_ExecutionContext.Size(m)
}
func (m *ExecutionContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionContext.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionContext proto.InternalMessageInfo

func (m *ExecutionContext) GetStopTime() *timestamp.Timestamp {
	if m != nil {
		return m.StopTime
	}
	return nil
}

func (m *ExecutionContext) GetEnvVars() []*EnvironmentVariable {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

type Result struct {
	EnvVars              []*EnvironmentVariable `protobuf:"bytes,1,rep,name=envVars,proto3" json:"envVars,omitempty"`
	Data                 []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Status               int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5c3996a00beb420, []int{3}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetEnvVars() []*EnvironmentVariable {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *Result) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Result) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*EnvironmentVariable)(nil), "fnrun.protobuf.EnvironmentVariable")
	proto.RegisterType((*Event)(nil), "fnrun.protobuf.Event")
	proto.RegisterType((*ExecutionContext)(nil), "fnrun.protobuf.ExecutionContext")
	proto.RegisterType((*Result)(nil), "fnrun.protobuf.Result")
}

func init() { proto.RegisterFile("fnrun.proto", fileDescriptor_a5c3996a00beb420) }

var fileDescriptor_a5c3996a00beb420 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0xa5, 0x9b, 0x9b, 0x9a, 0x8a, 0x4a, 0x14, 0x29, 0xf3, 0x60, 0xa9, 0x08, 0x3d, 0x65, 0x30,
	0x41, 0xbc, 0x88, 0xa0, 0xf4, 0x0f, 0x84, 0xb1, 0x83, 0xb7, 0x54, 0xbf, 0xd5, 0x40, 0x9a, 0x94,
	0xe4, 0x4b, 0xd9, 0x5f, 0xf0, 0x5f, 0x8b, 0xe9, 0x5a, 0xa7, 0x78, 0xf1, 0xf6, 0xde, 0xe3, 0x7b,
	0x2f, 0xef, 0x11, 0x12, 0xaf, 0xb5, 0xf5, 0x9a, 0x35, 0xd6, 0xa0, 0xa1, 0xc7, 0x3b, 0xa4, 0xf4,
	0xeb, 0xd9, 0x55, 0x65, 0x4c, 0xa5, 0x60, 0xde, 0x0b, 0x73, 0x94, 0x35, 0x38, 0x14, 0x75, 0xd3,
	0xdd, 0x64, 0x8f, 0xe4, 0xac, 0xd0, 0xad, 0xb4, 0x46, 0xd7, 0xa0, 0x71, 0x25, 0xac, 0x14, 0xa5,
	0x02, 0x4a, 0xc9, 0x9e, 0x16, 0x35, 0x24, 0x51, 0x1a, 0xe5, 0x87, 0x3c, 0x60, 0x7a, 0x4e, 0x26,
	0xad, 0x50, 0x1e, 0x92, 0x51, 0x10, 0x3b, 0x92, 0x5d, 0x92, 0x49, 0xd1, 0x82, 0xc6, 0x2f, 0xcb,
	0x9b, 0x40, 0x11, 0x2c, 0x47, 0x3c, 0xe0, 0xec, 0x23, 0x22, 0xa7, 0xc5, 0x06, 0x5e, 0x3d, 0x4a,
	0xa3, 0x9f, 0x8d, 0x46, 0xd8, 0x20, 0xbd, 0x23, 0x07, 0x0e, 0x4d, 0xb3, 0x94, 0xdb, 0xfc, 0x78,
	0x31, 0x63, 0x5d, 0xcd, 0xa1, 0x37, 0x5b, 0xf6, 0x35, 0xf9, 0x70, 0x4b, 0x1f, 0xc8, 0x3e, 0xe8,
	0x76, 0x25, 0xac, 0x4b, 0x46, 0xe9, 0x38, 0x8f, 0x17, 0xd7, 0xec, 0xe7, 0x5a, 0xf6, 0xc7, 0x12,
	0xde, 0x7b, 0x32, 0x47, 0xa6, 0x1c, 0x9c, 0x57, 0xb8, 0x1b, 0x14, 0xfd, 0x3f, 0x68, 0x18, 0x3a,
	0xfa, 0x1e, 0x4a, 0x2f, 0xc8, 0xd4, 0xa1, 0x40, 0xef, 0x92, 0x71, 0x1a, 0xe5, 0x13, 0xbe, 0x65,
	0x4f, 0xf7, 0xe4, 0x46, 0x1a, 0x56, 0x49, 0x7c, 0xf7, 0x25, 0x43, 0x70, 0x0e, 0x94, 0x12, 0x68,
	0xec, 0xaf, 0x07, 0xdd, 0xcb, 0x49, 0x10, 0x86, 0x7f, 0x72, 0xe5, 0x34, 0xc0, 0xdb, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0xad, 0xa1, 0xe2, 0xdf, 0x01, 0x00, 0x00,
}
